language: python

sudo: false

env:
    - TARGET=unit
    - TARGET=sever_ldap

python:
    - "3.4"

services:
    - mongodb
    - elasticsearch
    - redis-server

cache:
  directories:
    - $HOME/.cache/pip

install:
    - pip install .
    - pip install -r requirements.txt
    - pip install coveralls==1.0a2;

script:
    - if [ "${TARGET}" = "unit" ]; then
        flake8 ;
        nosetests --with-coverage --cover-package=superdesk ;
        behave --format progress2 --logging-level ERROR ;
      fi

    - if [ "${TARGET}" = "server_ldap" ]; then
        LDAP_SERVER="ldap://sourcefabric.org" LDAP_BASE_FILTER="OU=Superdesk Users,dc=sourcefabric,dc=org" behave ./features/ --format progress2 --logging-level ERROR ;
      fi
